### ISSUE TITLE
Not working on FOS v7.2.6

### ISSUE THREAD

**Issue by taduo** [fwsec/fgt-webui-tools#1]
Firefox:
![image](https://github.com/fwsec/fgt-webui-tools/assets/65782880/64a94f1c-9334-4e19-9768-651da113f5b5)

Google Chrome:
![image](https://github.com/fwsec/fgt-webui-tools/assets/65782880/dcb895d5-8118-4ef7-a9c5-f50795e52200)

**Comment by fwsec** [comment]
Fixed in version 0.2.6
